### ISSUE TITLE
In block select mode, I can't type characters on all lines

### ISSUE THREAD

**Issue by vi** [hlamer/enki#333] opened 2015-11-04 02:49 UTC
**tl;dr**: Enki should also do this: http://defun.co/uJm6

Suppose I have block-selected the upper case characters:

```
qweRTyuio
asdFGhjkl
zxcVBnm,.
```

The cursor is on the right (i.e. selected from left to right).

In Insert mode, I expect tying `12` to produce:

```
qweRT12yuio
asdFG12hjkl
zxcVB12nm,.
```

In Replace mode, I expect typing `12` to produce:

```
qweRT12io
asdFG12kl
zxcVB12,.
```

Too short lines should be just appended.

**Comment by hlamer** [comment] 2015-11-14 05:34
Duplicate of #122

**Closed by hlamer** 2015-11-14 05:34 UTC
Labels: feature
