### ISSUE TITLE
v15.11.1: Preview is not visible

### ISSUE THREAD

**Issue by vi** [hlamer/enki#386] opened 2016-02-10 14:57 UTC
```
Traceback (most recent call last):
  File "/mnt/src/git/enki/bin/../enki/plugins/preview/preview.py", line 398, in run
    self.htmlReady.emit(task.filePath, html, errString, url)
UnboundLocalError: local variable 'html' referenced before assignment
```

**Comment by vi** [comment] 2016-02-10 15:16
Is not reproducible in master.

**Comment by hlamer** [comment] 2016-02-11 07:05
But the bug still exists. 
@bjones1, will you have time to check it?
`exepthook` in `main.py` shows an exception as a messagebox.

**Comment by bjones1** [comment] 2016-02-11 16:04
I'm confused. If the bug can't be reproduced in master, my assumption is that it was fixed by the additional commits. Is there a case where this happens in master?

**Comment by vi** [comment] 2016-02-11 16:20
If really needed I can try bisecting.

**Comment by hlamer** [comment] 2016-02-12 08:10
@bjones1, I haven't seen the bug but I see that after [this](https://github.com/hlamer/enki/blob/master/enki/plugins/preview/preview.py#L399) the traceback will happen because `html` is not defined.

**Comment by bjones1** [comment] 2016-02-12 17:51
Good point. I'll move the emit inside the try/catch. Eventually, I would like to send the exception back to the main thread.

**Comment by hlamer** [comment] 2016-02-23 08:16
@bjones1, will you have time for this issue in the near future? I'm near to release Py3-Qt5 based Enki

**Comment by bjones1** [comment] 2016-02-24 04:29
I think so. There are a couple of other nitpicks to fix, I'll also file issues as soon as I can.

**Comment by bjones1** [comment] 2016-03-16 16:48
Finally, I just pushed an update which addresses this, plus provides some cleanup of the preview plugin.

**Closed by bjones1** 2016-03-16 16:48 UTC
Labels: bug
