### ISSUE TITLE
Error on pressing ctrl+pgdown

### ISSUE THREAD

**Issue by Yajo** [hlamer/enki#255] opened 2015-02-17 09:41 UTC
After updating to version 14.07.2, when I press `Ctrl+PgDown` to go to the next document, this dialog appears. Also when I write anything:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/enki/plugins/preview/preview.py", line 277, in _restoreScrollPos
        self.previewSync.syncTextToPreview()
      File "/usr/lib/python2.7/site-packages/enki/plugins/preview/preview_sync.py", line 557, in syncTextToPreview
        webIndex = findApproxTextInTarget(qp.text, qp.textCursor().position(), mf.toPlainText())
      File "/usr/lib/python2.7/site-packages/enki/plugins/preview/approx_match.py", line 199, in findApproxTextInTarget
        match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
      File "/usr/lib/python2.7/site-packages/enki/plugins/preview/approx_match.py", line 150, in findApproxText
        match = pat.search(targetText, fz)
    TypeError: must be string, not unicode

**Comment by bjones1** [comment] 2015-02-17 18:21
I can't reproduce this. Since I authored the preview sync code, would you mind giving me a few more details on how? For me, using Windows 7, Python 2.7, creating a blank document or opening several and typing in them works fine with 14.07.2.

Also, what version of TRE are you using? You need a build-from-source flavor; if you're on Linux, what distro?

Thanks!

**Comment by Yajo** [comment] 2015-02-18 08:11
Hi. I'm using a prebuilt version on Fedora 21. You can check the source code and how it was built on [my repository page](https://build.opensuse.org/project/show/home:yajo:enki) (it's the one I'm using to try to package it officially for Fedora).

TRE versions: python-tre-0.8.0-12.fc21 and tre-0.8.0-12.fc21.

**Comment by bjones1** [comment] 2015-02-18 15:20
OK, thanks. I'll build a Fedora 21 machine and test. I'm almost certain its python-tre, which doesn't support unicode. I'll work on a fix for Enki that detects this and disables the preview sync feature. Would you mind testing with the unicode-enabled python-tre? To do so (ubuntu -- please update for Fedora):

```
sudo apt-get install git build-essential autotools-dev automake gettext libtool autopoint zip python-dev python-pip
git clone https://github.com/bjones1/tre.git
cd tre
./utils/autogen.sh
./configure
make
sudo make install
cd python
sudo python setup.py install
# Note: the line below should be added to your .bashrc.
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```

**Comment by bjones1** [comment] 2015-02-18 20:33
Some perhaps simple questions: how can I download or install the enki package (and the python-qutepart, python-codechat dependencies) you created? Is there some sort of yum install, or down I download rpms?

**Comment by Yajo** [comment] 2015-02-19 09:33
Follow instructions [here](http://software.opensuse.org/download.html?project=home%3Ayajo%3Aenki&package=enki) for Fedora.

**Comment by bjones1** [comment] 2015-02-19 18:31
Thanks. I've reproduced the error and am working on a fix.

**Comment by bjones1** [comment] 2015-02-19 23:24
Andrei, I've got what seems to fix the bug in my repo. However, I can't run all unit tests on fc21 because of a crash. Testing just on the current master:

```
[bjones@localhost test_plugins]$ python -m unittest -v test_navigator
test_1 (test_navigator.Gui) ... ok
test_2 (test_navigator.Gui) ... ok
test_3 (test_navigator.Gui) ... ok
test_4 (test_navigator.Gui) ... ok
test_5 (test_navigator.Gui) ... ok
test_6 (test_navigator.Gui) ... ok
test_7 (test_navigator.Gui) ... ok
test_8 (test_navigator.Gui) ... ok
test_1 (test_navigator.Parser) ... ok
test_2 (test_navigator.Parser) ... ok
test_3 (test_navigator.Parser)
Ignore warning from ctags ... ok
test_1 (test_navigator.Settings) ... ok
test_2 (test_navigator.Settings)
Warning about etags ... Segmentation fault (core dumped)
[bjones@localhost test_plugins]$ python -m unittest -v test_navigator
test_1 (test_navigator.Gui) ... ok
test_2 (test_navigator.Gui) ... ok
test_3 (test_navigator.Gui) ... ok
test_4 (test_navigator.Gui) ... ok
test_5 (test_navigator.Gui) ... ok
test_6 (test_navigator.Gui) ... ok
test_7 (test_navigator.Gui) ... ok
test_8 (test_navigator.Gui) ... ok
test_1 (test_navigator.Parser) ... ok
test_2 (test_navigator.Parser) ... ok
test_3 (test_navigator.Parser)
Ignore warning from ctags ... ok
test_1 (test_navigator.Settings) ... ok
test_2 (test_navigator.Settings)
Warning about etags ... Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/qutepart/completer.py", line 52, in _onTimer
    method()
  File "/usr/lib/python2.7/site-packages/qutepart/completer.py", line 367, in _updateWordSet
    for line in self._qpart.lines:
  File "/usr/lib/python2.7/site-packages/qutepart/lines.py", line 150, in __iter__
    return self._Iterator(self._doc.firstBlock())
RuntimeError: wrapped C/C++ object of type QTextDocument has been deleted
ok
test_3 (test_navigator.Settings) ... ok

----------------------------------------------------------------------
Ran 14 tests in 6.937s

OK
```

**Comment by bjones1** [comment] 2015-02-20 03:31
Oops. This is probably my mistake -- I was testing using qutepart from the 14.07.2 release, instead of qutepart head. Let me re-try.

**Comment by bjones1** [comment] 2015-02-20 12:31
Still getting seg faults when I test master qutepart + master enki on Fedora 21 (I'm using 32-bit -- don't know if that matters). Andrei, would you check?

**Comment by hlamer** [comment] 2015-02-20 12:33
I will

**Comment by hlamer** [comment] 2015-02-20 15:09
I downloaded 32 image from getfedora.org and executed tests. Can not reproduce the crash.
@bjones1 , is it reproduced stable for you?

**Comment by bjones1** [comment] 2015-02-23 22:15
Yes. However, perhaps installing Yajo's pre-built version then master qutepart and enki on top of that confused something. Let me rebuild a clean image and retest.

**Comment by bjones1** [comment] 2015-02-23 23:11
A clean image still produces regular segfaults. The output is similar to what I posted above. If it helps, I installed based on the script in win/enki_install.sh, with a few modifications for Fedora. Here it is. What can I do next?

```
#!/bin/sh
#
# *******************
# Enki install script
# *******************
# This script installs Enki and its dependencies from source. It is tested on
# Ubuntu 12.04.
#
# Common commands
# ===============
# Echo all commands.
set -o verbose
# Set up alias for repeated commands.
PAUSE="read -p Press_[Enter]_to_continue... junk"
INSTALL="sudo apt-get install -y"
#INSTALL="sudo yum install -y" # Fedora
#
# Source code and installs
# ========================
# Put everything in ``enki_all``.
mkdir enki_all
cd enki_all

# Note: I skipped TRE and CodeChat installs, to test my fixes for those.

# Qutepart
# ========
$INSTALL libpcre3 libpcre3-dev python-qt4 # On Fedora, use pcre, pcre-devel.
# See https://github.com/hlamer/qutepart.
git clone https://github.com/bjones1/qutepart.git
cd qutepart
# See https://help.github.com/articles/adding-a-remote/.
git remote add upstream https://github.com/hlamer/qutepart.git
sudo python setup.py install
$PAUSE
cd ..

# Enki
# ====
$INSTALL desktop-file-utils exuberant-ctags # On Fedora, use ctags.
# Then install Python packages from pip, since apt-get packages are older.
sudo pip install -U mock pyparsing markdown sphinx pylint
# See https://github.com/bjones1/enki.
git clone https://github.com/bjones1/enki.git
cd enki
git remote add upstream https://github.com/hlamer/enki.git
$PAUSE
cd ..

cd ..
```

**Comment by hlamer** [comment] 2015-02-24 07:26
Checked your script and made my setup similar to yours. Still don't have the crash. Yes, .vdi would be helpful.

**Comment by bjones1** [comment] 2015-02-24 16:44
OK, I've placed my VirtualBox machine files here: https://www.dropbox.com/sh/2tg2ufk6wkw96xy/AABoCaP--MxCRQF_dxedZDEva?dl=0.

**Comment by hlamer** [comment] 2015-02-25 06:42
What is password for this VM?
(If you use the same password for something else, don't tell me it. It is better to reupload the vm)

**Comment by bjones1** [comment] 2015-02-25 14:00
Aargh. I re-uploaded using the password AndreiKopats.

**Comment by hlamer** [comment] 2015-02-26 07:30
OK, I've reproduced the crash. Will try to fix

**Comment by bjones1** [comment] 2015-02-26 12:21
Great. Thanks for your persistence. These garbage-collection bugs (I *think* that's what it is) are really hard to track down.

**Comment by hlamer** [comment] 2015-02-27 09:09
@bjones1, your vm uses your qutepart/master, which doesn't contain my last commit https://github.com/hlamer/qutepart/commit/11a91ad43767f443c4f0c8ccb0042ef7977b5a97.

Btw, I see 2 not merged commits your master.

**Closed by hlamer** 2015-02-27 09:09 UTC
Labels: bug

**Comment by bjones1** [comment] 2015-02-27 18:04
Aargh. I can't believe I didn't push those (I had them on my Windows PC...but obviously not in any cloned repo). My apologies. All tests pass for me now. I've submitted pull request #257 to fix this in master. If this works for you, I assume I should rebase it to 14.07.02?
