### ISSUE TITLE
Feature Request: Recognize comments

### ISSUE THREAD

**Issue by rovf** [hlamer/enki#320] opened 2015-10-16 11:12 UTC
It would be very handy to be able to comment/uncomment a group of lines, according to the syntax of the current language.

Also, it would be handy to have the possibility to have automatic line wrap (auto-formatting) inside block comments only, but no line wrapping outside block comments.

**Comment by hlamer** [comment] 2015-10-18 08:26
Yes, very useful feature.

**Comment by hlamer** [comment] 2015-11-14 05:35
Duplicate of #193

**Closed by hlamer** 2015-11-14 05:35 UTC
Labels: feature
